package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	public static final SysDict dao = new SysDict().dao();
}
