package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	public List<SysMenu> findAll() {
		return find("select * from sys_menu order by order_num asc");
	}
	
	public List<SysMenu> findByRoleIds(String roleIds) {
		return find("select distinct b.* from sys_role_menu a join sys_menu b on a.menu_id=b.id where role_id in(" + roleIds + ")");
	}
}
