package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysOplog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOplog extends BaseSysOplog<SysOplog> {
	public static final SysOplog dao = new SysOplog().dao();
}
