package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysRoleDatarule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleDatarule extends BaseSysRoleDatarule<SysRoleDatarule> {
	public static final SysRoleDatarule dao = new SysRoleDatarule().dao();
}
