package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysRoleBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleBtn extends BaseSysRoleBtn<SysRoleBtn> {
	public static final SysRoleBtn dao = new SysRoleBtn().dao();
}
