package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysRoleMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	public static final SysRoleMenu dao = new SysRoleMenu().dao();
	
	public List<SysRoleMenu> findByIds(String ids) {
		return find("select * from sys_role_menu where id in(" + ids + ")");
	}
	
	public int countByRoleIdAndMenuId(Integer roleId, Integer menuId) {
		return find("select * from sys_role_menu where role_id=? and menu_id=?", roleId, menuId).size();
	}
}
