package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseSysUser;
import net.inconnection.charge.admin.common.DbMetaTool;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser().dao();
	
	public SysUser findByUserNameAndPassword(String userName, String password) {
		return findFirst("select * from sys_user where user_name=? and password=?", new Object[]{userName, password});
	}
	
	public Map<String, Object> getDictDataroles() {
		return DbMetaTool.getDictData("select id, role_name from sys_role");
	}
}
