package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseTaskBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskBase extends BaseTaskBase<TaskBase> {
	public static final TaskBase dao = new TaskBase().dao();
}
