package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseTbProcLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProcLog extends BaseTbProcLog<TbProcLog> {
	public static final TbProcLog dao = new TbProcLog().dao();
}
