package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseZcurdHead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcurdHead extends BaseZcurdHead<ZcurdHead> {
	public static final ZcurdHead dao = new ZcurdHead().dao();
}
