package net.inconnection.charge.admin.account.model;


import net.inconnection.charge.admin.account.model.base.BaseZcurdHeadJs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcurdHeadJs extends BaseZcurdHeadJs<ZcurdHeadJs> {
	public static final ZcurdHeadJs dao = new ZcurdHeadJs().dao();
}
