package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseBMap;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BMap extends BaseBMap<BMap> {
	public static final BMap dao = new BMap().dao();
}
