package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Card extends BaseCard<Card> {
	public static final Card dao = new Card().dao();
}
