package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCardlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cardlog extends BaseCardlog<Cardlog> {
	public static final Cardlog dao = new Cardlog().dao();

	public static final Cardlog me = new Cardlog();
}
