package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargePile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargePile extends BaseChargePile<ChargePile> {
	public static final ChargePile dao = new ChargePile().dao();
}
