package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargePile;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargePile extends BaseChargePile<ChargePile> {
	public static final ChargePile dao = new ChargePile().dao();

    public List<ChargePile> queryDeviceLocation() {
        List<ChargePile> chargePiles = dao.find("select * from yc_charge_pile where lat is not null and lng is not " +
                "null");
        return chargePiles;
    }
}
