package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeHistory extends BaseChargeHistory<ChargeHistory> {
	public static final ChargeHistory dao = new ChargeHistory().dao();
}
