package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargePileHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargePileHistory extends BaseChargePileHistory<ChargePileHistory> {
	public static final ChargePileHistory dao = new ChargePileHistory().dao();
}
