package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeSocketHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeSocketHistory extends BaseChargeSocketHistory<ChargeSocketHistory> {
	public static final ChargeSocketHistory dao = new ChargeSocketHistory().dao();
}
