package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeBatteryInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeBatteryInfo extends BaseChargeBatteryInfo<ChargeBatteryInfo> {
	public static final ChargeBatteryInfo dao = new ChargeBatteryInfo().dao();
	public static final ChargeBatteryInfo me = new ChargeBatteryInfo();
}
