package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeprice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chargeprice extends BaseChargeprice<Chargeprice> {
	public static final Chargeprice dao = new Chargeprice().dao();
	public static final Chargeprice me = new Chargeprice();
}
