package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargePileHardwareVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargePileHardwareVersion extends BaseChargePileHardwareVersion<ChargePileHardwareVersion> {
	public static final ChargePileHardwareVersion dao = new ChargePileHardwareVersion().dao();
}
