package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargestatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chargestatus extends BaseChargestatus<Chargestatus> {
	public static final Chargestatus dao = new Chargestatus().dao();
}
