package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeSocket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeSocket extends BaseChargeSocket<ChargeSocket> {
	public static final ChargeSocket dao = new ChargeSocket().dao();
}
