package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseChargeMoneyInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeMoneyInfo extends BaseChargeMoneyInfo<ChargeMoneyInfo> {
	public static final ChargeMoneyInfo dao = new ChargeMoneyInfo().dao();
	public static final ChargeMoneyInfo me = new ChargeMoneyInfo();
}
