package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Charge extends BaseCharge<Charge> {
	public static final Charge dao = new Charge().dao();
}
