package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCommand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Command extends BaseCommand<Command> {
	public static final Command dao = new Command().dao();
}
