package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCompanyActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyActivity extends BaseCompanyActivity<CompanyActivity> {
	public static final CompanyActivity dao = new CompanyActivity().dao();
}
