package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company().dao();
	public static final Company me = new Company();
}
