package net.inconnection.charge.extend.model;

import com.jfinal.log.Log;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import net.inconnection.charge.admin.account.common.annotation.ClearAuth;
import net.inconnection.charge.admin.account.model.SysUser;
import net.inconnection.charge.admin.common.ZcurdTool;
import net.inconnection.charge.extend.model.base.BaseCompany;

import java.util.ArrayList;
import java.util.List;

import static net.inconnection.charge.admin.account.common.kit.ZcurdKit.getSessionUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
    private static final Log log = Log.getLog(Company.class);
	public static final Company dao = new Company().dao();
	public static final Company me = new Company();

    public List<Company> findAll() {
        return dao.find("select * from yc_company");
    }

    @ClearAuth
    public List<Company> getCompanyListByLoginUser(){
        Company company = Company.dao.getCompanyByLoginUser();
        if(1 == company.getId()){
            return Company.me.findAll();
        }
        List<Company> list = new ArrayList<Company>();
        list.add(company);
        return list;
    }

    public List<Company> getCompanyByAgentId(Long userId ) {
        log.info("查询用户拥有的所有公司的id:" );
        List<Company> companies = dao.find("select * from yc_company where admin_id = ?" ,new Object[]{userId});
        log.info("查询所有运营商公司信息:" + companies);
        return companies;
    }

    public Company getCompanyByLoginUser() {
        log.info("查询登录用户拥有的所有公司的id:" );
        SysUser sysUser = getSessionUser();
        List<Record> userCompanyList = Db.use(ZcurdTool.getDbSource("zcurd_busi")).find("select * from " +
                "sysuser_company where sysuser_id="+sysUser.getId());
        StringBuffer id= new StringBuffer();
        for (int i = 0; i < userCompanyList.size(); i++) {
            Record record = userCompanyList.get(i);
            String companyId = record.get("company_id").toString();
            id.append(companyId).append(",");
        }

        Company company = this.dao().findFirst("select * from yc_company where id in (" + id.substring(0,id.length()-1) + ")");
        return company;
    }

}
