package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config().dao();
}
