package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
	public static final Coupon dao = new Coupon().dao();
}
