package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer().dao();
}
