package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDeviceCsq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceCsq extends BaseDeviceCsq<DeviceCsq> {
	public static final DeviceCsq dao = new DeviceCsq().dao();
}
