package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDevicelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicelog extends BaseDevicelog<Devicelog> {
	public static final Devicelog dao = new Devicelog().dao();
}
