package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDeviceport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deviceport extends BaseDeviceport<Deviceport> {
	public static final Deviceport dao = new Deviceport().dao();
}
