package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDeviceLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceLocation extends BaseDeviceLocation<DeviceLocation> {
	public static final DeviceLocation dao = new DeviceLocation().dao();
}
