package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDevicemsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicemsg extends BaseDevicemsg<Devicemsg> {
	public static final Devicemsg dao = new Devicemsg().dao();
}
