package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseDroppedlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Droppedlog extends BaseDroppedlog<Droppedlog> {
	public static final Droppedlog dao = new Droppedlog().dao();
}
