package net.inconnection.charge.extend.model;


import net.inconnection.charge.extend.model.base.BaseGiftRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GiftRefund extends BaseGiftRefund<GiftRefund> {
    public static final GiftRefund me = new GiftRefund();
	public static final GiftRefund dao = new GiftRefund().dao();
}
