package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Images extends BaseImages<Images> {
	public static final Images dao = new Images().dao();
}
