package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseLostcard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lostcard extends BaseLostcard<Lostcard> {
	public static final Lostcard dao = new Lostcard().dao();
}
