package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseMoneyMatchActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MoneyMatchActivity extends BaseMoneyMatchActivity<MoneyMatchActivity> {
	public static final MoneyMatchActivity dao = new MoneyMatchActivity().dao();
}
