package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	public static final Orders dao = new Orders().dao();
}
