package net.inconnection.charge.extend.model;

import com.jfinal.log.Log;
import net.inconnection.charge.extend.model.base.BasePayAgentHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayAgentHistory extends BasePayAgentHistory<PayAgentHistory> {
    private static Log log = Log.getLog(PayAgentHistory.class);

    public static final PayAgentHistory dao = new PayAgentHistory().dao();
    public static final PayAgentHistory me = new PayAgentHistory();

    public PayAgentHistory queryPayAgentHistory(long companyId) {
        return this.findFirst("select * from yc_pay_agent_history where company_id = ?  ORDER BY operator_time desc", companyId);
    }

}
