package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePayLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayLog extends BasePayLog<PayLog> {
	public static final PayLog dao = new PayLog().dao();
}
