package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePayNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayNotify extends BasePayNotify<PayNotify> {
	public static final PayNotify dao = new PayNotify().dao();
}
