package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePayToAgentReq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayToAgentReq extends BasePayToAgentReq<PayToAgentReq> {
	public static final PayToAgentReq dao = new PayToAgentReq().dao();
}
