package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePayToAgentResp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayToAgentResp extends BasePayToAgentResp<PayToAgentResp> {
	public static final PayToAgentResp dao = new PayToAgentResp().dao();
}
