package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePileCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PileCard extends BasePileCard<PileCard> {
    public static final PileCard me = new PileCard();
	public static final PileCard dao = new PileCard().dao();

	public PileCard queryPileCardByColumn(String column,String value){
        PileCard pileCard = me.findFirst("select * from yc_pile_card where " + column + "= ? ", value);
        return pileCard;
    }
}
