package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BasePowerDevicePort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PowerDevicePort extends BasePowerDevicePort<PowerDevicePort> {
	public static final PowerDevicePort dao = new PowerDevicePort().dao();
}
