package net.inconnection.charge.extend.model;

import com.jfinal.log.Log;
import net.inconnection.charge.extend.model.base.BaseCompanyActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectActivity extends BaseCompanyActivity<ProjectActivity> {
    private static Log log = Log.getLog(ProjectActivity.class);

    public static final ProjectActivity dao = new ProjectActivity().dao();
    public static final ProjectActivity me = new ProjectActivity();
    public ProjectActivity queryProjectActivityByProjectIdAndActNum(String projectId,String actNum) {
        log.info("根据projectId和actNum查询活动信息:projectId=" + projectId+"actNum="+actNum);
        ProjectActivity projectActivity = (ProjectActivity)this.findFirst("select * from yc_project_activity where project_id = ? and actNum = ?", new Object[]{projectId,actNum});
        log.info("根据projectId和actNum查询活动信息:" + projectActivity);
        return projectActivity;
    }
}
