package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseQrMatchDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrMatchDevice extends BaseQrMatchDevice<QrMatchDevice> {
	public static final QrMatchDevice dao = new QrMatchDevice().dao();
}
