package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseQrMatchDevice;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrMatchDevice extends BaseQrMatchDevice<QrMatchDevice> {
	public static final QrMatchDevice dao = new QrMatchDevice().dao();
	public static final QrMatchDevice me = new QrMatchDevice();

	public QrMatchDevice() {
	}

	public List<QrMatchDevice> findAll() {
		return this.find("select * from qr_match_device order by createtime asc");
	}

	public List<QrMatchDevice> findByGid(long gid) {
		return this.find("select * from qr_match_device where gid=" + gid + " order by createtime asc");
	}

	public List<QrMatchDevice> findInGid(String gid) {
		return this.find("select * from qr_match_device where gid in (" + gid + ") order by createtime asc");
	}

    public QrMatchDevice findByQrNum(Long qrNum) {
        return this.findFirst("select * from qr_match_device where qr_num = ? " ,qrNum);
    }
}
