package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseRechargeHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargeHistory extends BaseRechargeHistory<RechargeHistory> {
	public static final RechargeHistory dao = new RechargeHistory().dao();
}
