package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseRechargeHistory;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargeHistory extends BaseRechargeHistory<RechargeHistory> {
	public static final RechargeHistory dao = new RechargeHistory().dao();

    public List<RechargeHistory> queryRechargeHistory(long companyId, Date startDate, Date endDate) {
        List<RechargeHistory> rechargeHistories = this.find("select * from yc_recharge_history where company_id = ? " +
                "and recharge_time > ? and recharge_time < ?", companyId, startDate, endDate);
        return rechargeHistories;

    }
}
