package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseSendWeixinMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SendWeixinMessage extends BaseSendWeixinMessage<SendWeixinMessage> {
	public static final SendWeixinMessage dao = new SendWeixinMessage().dao();
}
