package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseTuserCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TuserCharge extends BaseTuserCharge<TuserCharge> {
	public static final TuserCharge dao = new TuserCharge().dao();
}
