package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseTuserAndCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TuserAndCoupon extends BaseTuserAndCoupon<TuserAndCoupon> {
	public static final TuserAndCoupon dao = new TuserAndCoupon().dao();
}
