package net.inconnection.charge.extend.model;

import net.inconnection.charge.extend.model.base.BaseWeixinToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinToken extends BaseWeixinToken<WeixinToken> {
	public static final WeixinToken dao = new WeixinToken().dao();
}
