package net.inconnection.charge.admin.online.model;


import net.inconnection.charge.admin.online.model.base.BaseTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskLog extends BaseTaskLog<TaskLog> {
	public static final TaskLog dao = new TaskLog().dao();
}
