package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrMatchDevice<M extends BaseQrMatchDevice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGid(java.lang.Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	public M setGname(java.lang.String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public java.lang.String getGname() {
		return getStr("gname");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setQrNum(java.lang.String qrNum) {
		set("qr_num", qrNum);
		return (M)this;
	}
	
	public java.lang.String getQrNum() {
		return getStr("qr_num");
	}

	public M setMatchNum(java.lang.String matchNum) {
		set("match_num", matchNum);
		return (M)this;
	}
	
	public java.lang.String getMatchNum() {
		return getStr("match_num");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setTowHoursPrice(java.lang.Integer towHoursPrice) {
		set("tow_hours_price", towHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTowHoursPrice() {
		return getInt("tow_hours_price");
	}

	public M setFourHoursPrice(java.lang.Integer fourHoursPrice) {
		set("four_hours_price", fourHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getFourHoursPrice() {
		return getInt("four_hours_price");
	}

	public M setEightHoursPrice(java.lang.Integer eightHoursPrice) {
		set("eight_hours_price", eightHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getEightHoursPrice() {
		return getInt("eight_hours_price");
	}

	public M setTwelveHoursPrice(java.lang.Integer twelveHoursPrice) {
		set("twelve_hours_price", twelveHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTwelveHoursPrice() {
		return getInt("twelve_hours_price");
	}

	public M setTowHoursMemPrice(java.lang.Integer towHoursMemPrice) {
		set("tow_hours_mem_price", towHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTowHoursMemPrice() {
		return getInt("tow_hours_mem_price");
	}

	public M setFourHoursMemPrice(java.lang.Integer fourHoursMemPrice) {
		set("four_hours_mem_price", fourHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getFourHoursMemPrice() {
		return getInt("four_hours_mem_price");
	}

	public M setEightHoursMemPrice(java.lang.Integer eightHoursMemPrice) {
		set("eight_hours_mem_price", eightHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getEightHoursMemPrice() {
		return getInt("eight_hours_mem_price");
	}

	public M setTwelveHoursMemPrice(java.lang.Integer twelveHoursMemPrice) {
		set("twelve_hours_mem_price", twelveHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTwelveHoursMemPrice() {
		return getInt("twelve_hours_mem_price");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setAutoPrice(java.lang.Integer autoPrice) {
		set("auto_price", autoPrice);
		return (M)this;
	}
	
	public java.lang.Integer getAutoPrice() {
		return getInt("auto_price");
	}

	public M setPowerA1(java.lang.String powerA1) {
		set("power_a1", powerA1);
		return (M)this;
	}
	
	public java.lang.String getPowerA1() {
		return getStr("power_a1");
	}

	public M setPowerA2(java.lang.String powerA2) {
		set("power_a2", powerA2);
		return (M)this;
	}
	
	public java.lang.String getPowerA2() {
		return getStr("power_a2");
	}

	public M setPowerA3(java.lang.String powerA3) {
		set("power_a3", powerA3);
		return (M)this;
	}
	
	public java.lang.String getPowerA3() {
		return getStr("power_a3");
	}

	public M setPowerA4(java.lang.String powerA4) {
		set("power_a4", powerA4);
		return (M)this;
	}
	
	public java.lang.String getPowerA4() {
		return getStr("power_a4");
	}

	public M setPowerA5(java.lang.String powerA5) {
		set("power_a5", powerA5);
		return (M)this;
	}
	
	public java.lang.String getPowerA5() {
		return getStr("power_a5");
	}

	public M setPowerA6(java.lang.String powerA6) {
		set("power_a6", powerA6);
		return (M)this;
	}
	
	public java.lang.String getPowerA6() {
		return getStr("power_a6");
	}

	public M setPowerA7(java.lang.String powerA7) {
		set("power_a7", powerA7);
		return (M)this;
	}
	
	public java.lang.String getPowerA7() {
		return getStr("power_a7");
	}

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}
	
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	public M setFree(java.lang.String free) {
		set("free", free);
		return (M)this;
	}
	
	public java.lang.String getFree() {
		return getStr("free");
	}

	public M setPayToAgentStatus(java.lang.String payToAgentStatus) {
		set("pay_to_agent_status", payToAgentStatus);
		return (M)this;
	}
	
	public java.lang.String getPayToAgentStatus() {
		return getStr("pay_to_agent_status");
	}

	public M setPayToAgentOpenid(java.lang.String payToAgentOpenid) {
		set("pay_to_agent_openid", payToAgentOpenid);
		return (M)this;
	}
	
	public java.lang.String getPayToAgentOpenid() {
		return getStr("pay_to_agent_openid");
	}

	public M setPayToAgentName(java.lang.String payToAgentName) {
		set("pay_to_agent_name", payToAgentName);
		return (M)this;
	}
	
	public java.lang.String getPayToAgentName() {
		return getStr("pay_to_agent_name");
	}

}
