package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargeMoneyInfo<M extends BaseChargeMoneyInfo<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public String getOpenId() {
		return getStr("openId");
	}

	public M setMoney(Integer money) {
		set("money", money);
		return (M)this;
	}
	
	public Integer getMoney() {
		return getInt("money");
	}

	public M setAmount(Integer amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public Integer getAmount() {
		return getInt("amount");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setChargeType(String chargeType) {
		set("chargeType", chargeType);
		return (M)this;
	}
	
	public String getChargeType() {
		return getStr("chargeType");
	}

	public M setCardAmount(Integer cardAmount) {
		set("card_amount", cardAmount);
		return (M)this;
	}
	
	public Integer getCardAmount() {
		return getInt("card_amount");
	}

	public M setDeviceId(String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public String getDeviceId() {
		return getStr("deviceId");
	}

	public M setMD5(String MD5) {
		set("MD5", MD5);
		return (M)this;
	}
	
	public String getMD5() {
		return getStr("MD5");
	}

	public M setPayToAgentStatus(String payToAgentStatus) {
		set("pay_to_agent_status", payToAgentStatus);
		return (M)this;
	}
	
	public String getPayToAgentStatus() {
		return getStr("pay_to_agent_status");
	}

	public M setPayToAgentTime(java.util.Date payToAgentTime) {
		set("pay_to_agent_time", payToAgentTime);
		return (M)this;
	}
	
	public java.util.Date getPayToAgentTime() {
		return get("pay_to_agent_time");
	}

}
