package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCardlog<M extends BaseCardlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public java.lang.String getDeviceId() {
		return getStr("deviceId");
	}

	public M setPhyicalId(java.lang.String phyicalId) {
		set("phyicalId", phyicalId);
		return (M)this;
	}
	
	public java.lang.String getPhyicalId() {
		return getStr("phyicalId");
	}

	public M setCardCode(java.lang.String cardCode) {
		set("cardCode", cardCode);
		return (M)this;
	}
	
	public java.lang.String getCardCode() {
		return getStr("cardCode");
	}

	public M setBalance(java.lang.String balance) {
		set("balance", balance);
		return (M)this;
	}
	
	public java.lang.String getBalance() {
		return getStr("balance");
	}

	public M setJoinDate(java.util.Date joinDate) {
		set("joinDate", joinDate);
		return (M)this;
	}
	
	public java.util.Date getJoinDate() {
		return get("joinDate");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setGname(java.lang.String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public java.lang.String getGname() {
		return getStr("gname");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setChannelNum(java.lang.String channelNum) {
		set("channelNum", channelNum);
		return (M)this;
	}
	
	public java.lang.String getChannelNum() {
		return getStr("channelNum");
	}

	public M setGid(java.lang.Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

}
