package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceLocation<M extends BaseDeviceLocation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
		return (M)this;
	}
	
	public java.lang.String getDeviceid() {
		return getStr("deviceid");
	}

	public M setDevicename(java.lang.String devicename) {
		set("devicename", devicename);
		return (M)this;
	}
	
	public java.lang.String getDevicename() {
		return getStr("devicename");
	}

	public M setLac(java.lang.String lac) {
		set("lac", lac);
		return (M)this;
	}
	
	public java.lang.String getLac() {
		return getStr("lac");
	}

	public M setCid(java.lang.String cid) {
		set("cid", cid);
		return (M)this;
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}

	public M setLng(java.lang.String lng) {
		set("lng", lng);
		return (M)this;
	}
	
	public java.lang.String getLng() {
		return getStr("lng");
	}

	public M setLat(java.lang.String lat) {
		set("lat", lat);
		return (M)this;
	}
	
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public M setOlng(java.lang.String olng) {
		set("olng", olng);
		return (M)this;
	}
	
	public java.lang.String getOlng() {
		return getStr("olng");
	}

	public M setOlat(java.lang.String olat) {
		set("olat", olat);
		return (M)this;
	}
	
	public java.lang.String getOlat() {
		return getStr("olat");
	}

	public M setJointime(java.util.Date jointime) {
		set("jointime", jointime);
		return (M)this;
	}
	
	public java.util.Date getJointime() {
		return get("jointime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setUpdatenum(java.lang.Integer updatenum) {
		set("updatenum", updatenum);
		return (M)this;
	}
	
	public java.lang.Integer getUpdatenum() {
		return getInt("updatenum");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
