package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargePileHistory<M extends BaseChargePileHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPileId(java.lang.Long pileId) {
		set("pile_id", pileId);
		return (M)this;
	}
	
	public java.lang.Long getPileId() {
		return getLong("pile_id");
	}

	public M setPowerMax(java.lang.Long powerMax) {
		set("power_max", powerMax);
		return (M)this;
	}
	
	public java.lang.Long getPowerMax() {
		return getLong("power_max");
	}

	public M setSocketSum(java.lang.Long socketSum) {
		set("socket_sum", socketSum);
		return (M)this;
	}
	
	public java.lang.Long getSocketSum() {
		return getLong("socket_sum");
	}

	public M setTotalIntensity(java.lang.Long totalIntensity) {
		set("total_intensity", totalIntensity);
		return (M)this;
	}
	
	public java.lang.Long getTotalIntensity() {
		return getLong("total_intensity");
	}

	public M setTotalVoltage(java.lang.Long totalVoltage) {
		set("total_voltage", totalVoltage);
		return (M)this;
	}
	
	public java.lang.Long getTotalVoltage() {
		return getLong("total_voltage");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setBatVol(java.lang.Integer batVol) {
		set("bat_vol", batVol);
		return (M)this;
	}
	
	public java.lang.Integer getBatVol() {
		return getInt("bat_vol");
	}

	public M setControllerVol(java.lang.Integer controllerVol) {
		set("controller_vol", controllerVol);
		return (M)this;
	}
	
	public java.lang.Integer getControllerVol() {
		return getInt("controller_vol");
	}

	public M setPowerTotal(java.lang.Long powerTotal) {
		set("power_total", powerTotal);
		return (M)this;
	}
	
	public java.lang.Long getPowerTotal() {
		return getLong("power_total");
	}

}
