package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStockHistoryLog<M extends BaseStockHistoryLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDt(java.util.Date dt) {
		set("dt", dt);
		return (M)this;
	}
	
	public java.util.Date getDt() {
		return get("dt");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setClosingPrice(java.lang.Double closingPrice) {
		set("closing_price", closingPrice);
		return (M)this;
	}
	
	public java.lang.Double getClosingPrice() {
		return getDouble("closing_price");
	}

	public M setTopPrice(java.lang.Double topPrice) {
		set("top_price", topPrice);
		return (M)this;
	}
	
	public java.lang.Double getTopPrice() {
		return getDouble("top_price");
	}

	public M setMinimumPrice(java.lang.Double minimumPrice) {
		set("minimum_price", minimumPrice);
		return (M)this;
	}
	
	public java.lang.Double getMinimumPrice() {
		return getDouble("minimum_price");
	}

	public M setOpeningPrice(java.lang.Double openingPrice) {
		set("opening_price", openingPrice);
		return (M)this;
	}
	
	public java.lang.Double getOpeningPrice() {
		return getDouble("opening_price");
	}

	public M setPre(java.lang.Double pre) {
		set("pre", pre);
		return (M)this;
	}
	
	public java.lang.Double getPre() {
		return getDouble("pre");
	}

	public M setChangeAmount(java.lang.Double changeAmount) {
		set("change_amount", changeAmount);
		return (M)this;
	}
	
	public java.lang.Double getChangeAmount() {
		return getDouble("change_amount");
	}

	public M setChangeRatio(java.lang.Double changeRatio) {
		set("change_ratio", changeRatio);
		return (M)this;
	}
	
	public java.lang.Double getChangeRatio() {
		return getDouble("change_ratio");
	}

	public M setTurnoverVolume(java.lang.Long turnoverVolume) {
		set("turnover_volume", turnoverVolume);
		return (M)this;
	}
	
	public java.lang.Long getTurnoverVolume() {
		return getLong("turnover_volume");
	}

	public M setTurnoverMoney(java.lang.Long turnoverMoney) {
		set("turnover_money", turnoverMoney);
		return (M)this;
	}
	
	public java.lang.Long getTurnoverMoney() {
		return getLong("turnover_money");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
