package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCardlog<M extends BaseCardlog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public String getDeviceId() {
		return getStr("deviceId");
	}

	public M setPhyicalId(String phyicalId) {
		set("phyicalId", phyicalId);
		return (M)this;
	}
	
	public String getPhyicalId() {
		return getStr("phyicalId");
	}

	public M setCardCode(String cardCode) {
		set("cardCode", cardCode);
		return (M)this;
	}
	
	public String getCardCode() {
		return getStr("cardCode");
	}

	public M setBalance(String balance) {
		set("balance", balance);
		return (M)this;
	}
	
	public String getBalance() {
		return getStr("balance");
	}

	public M setJoinDate(java.util.Date joinDate) {
		set("joinDate", joinDate);
		return (M)this;
	}
	
	public java.util.Date getJoinDate() {
		return get("joinDate");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setGname(String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public String getGname() {
		return getStr("gname");
	}

	public M setArea(String area) {
		set("area", area);
		return (M)this;
	}
	
	public String getArea() {
		return getStr("area");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public M setChannelNum(String channelNum) {
		set("channelNum", channelNum);
		return (M)this;
	}
	
	public String getChannelNum() {
		return getStr("channelNum");
	}

	public M setGid(Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public Integer getGid() {
		return getInt("gid");
	}

}
