package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePayLog<M extends BasePayLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
		return (M)this;
	}
	
	public java.util.Date getStarttime() {
		return get("starttime");
	}

	public M setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
		return (M)this;
	}
	
	public java.util.Date getEndtime() {
		return get("endtime");
	}

	public M setJointime(java.util.Date jointime) {
		set("jointime", jointime);
		return (M)this;
	}
	
	public java.util.Date getJointime() {
		return get("jointime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setMoney(java.lang.String money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.String getMoney() {
		return getStr("money");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

}
