package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGid(java.lang.Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	public M setGname(java.lang.String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public java.lang.String getGname() {
		return getStr("gname");
	}

	public M setKeya1value(java.lang.String keya1value) {
		set("keya1value", keya1value);
		return (M)this;
	}
	
	public java.lang.String getKeya1value() {
		return getStr("keya1value");
	}

	public M setKeya2value(java.lang.String keya2value) {
		set("keya2value", keya2value);
		return (M)this;
	}
	
	public java.lang.String getKeya2value() {
		return getStr("keya2value");
	}

	public M setKeyb1value(java.lang.String keyb1value) {
		set("keyb1value", keyb1value);
		return (M)this;
	}
	
	public java.lang.String getKeyb1value() {
		return getStr("keyb1value");
	}

	public M setKeyb2value(java.lang.String keyb2value) {
		set("keyb2value", keyb2value);
		return (M)this;
	}
	
	public java.lang.String getKeyb2value() {
		return getStr("keyb2value");
	}

	public M setControlvalue(java.lang.String controlvalue) {
		set("controlvalue", controlvalue);
		return (M)this;
	}
	
	public java.lang.String getControlvalue() {
		return getStr("controlvalue");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
