package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargeSocketHistory<M extends BaseChargeSocketHistory<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setChargeSocketId(Long chargeSocketId) {
		set("charge_socket_id", chargeSocketId);
		return (M)this;
	}
	
	public Long getChargeSocketId() {
		return getLong("charge_socket_id");
	}

	public M setStartPower(Double startPower) {
		set("start_power", startPower);
		return (M)this;
	}
	
	public Double getStartPower() {
		return getDouble("start_power");
	}

	public M setChargeIntensity(Double chargeIntensity) {
		set("charge_intensity", chargeIntensity);
		return (M)this;
	}
	
	public Double getChargeIntensity() {
		return getDouble("charge_intensity");
	}

	public M setChargeTime(Long chargeTime) {
		set("charge_time", chargeTime);
		return (M)this;
	}
	
	public Long getChargeTime() {
		return getLong("charge_time");
	}

	public M setChargeState(Integer chargeState) {
		set("charge_state", chargeState);
		return (M)this;
	}
	
	public Integer getChargeState() {
		return getInt("charge_state");
	}

	public M setUpdateTime(Long updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public Long getUpdateTime() {
		return getLong("update_time");
	}

}
