package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommand<M extends BaseCommand<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCommand(java.lang.String command) {
		set("command", command);
		return (M)this;
	}
	
	public java.lang.String getCommand() {
		return getStr("command");
	}

	public M setSleeptime(java.lang.Integer sleeptime) {
		set("sleeptime", sleeptime);
		return (M)this;
	}
	
	public java.lang.Integer getSleeptime() {
		return getInt("sleeptime");
	}

	public M setJointime(java.util.Date jointime) {
		set("jointime", jointime);
		return (M)this;
	}
	
	public java.util.Date getJointime() {
		return get("jointime");
	}

	public M setReamark(java.lang.String reamark) {
		set("reamark", reamark);
		return (M)this;
	}
	
	public java.lang.String getReamark() {
		return getStr("reamark");
	}

	public M setOrderd(java.lang.Integer orderd) {
		set("orderd", orderd);
		return (M)this;
	}
	
	public java.lang.Integer getOrderd() {
		return getInt("orderd");
	}

}
