package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCharge<M extends BaseCharge<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setGname(String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public String getGname() {
		return getStr("gname");
	}

	public M setGid(Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public Integer getGid() {
		return getInt("gid");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public M setCardnum(String cardnum) {
		set("cardnum", cardnum);
		return (M)this;
	}
	
	public String getCardnum() {
		return getStr("cardnum");
	}

	public M setCardcs(String cardcs) {
		set("cardcs", cardcs);
		return (M)this;
	}
	
	public String getCardcs() {
		return getStr("cardcs");
	}

	public M setChargenum(String chargenum) {
		set("chargenum", chargenum);
		return (M)this;
	}
	
	public String getChargenum() {
		return getStr("chargenum");
	}

	public M setMoney(String money) {
		set("money", money);
		return (M)this;
	}
	
	public String getMoney() {
		return getStr("money");
	}

	public M setTotal(String total) {
		set("total", total);
		return (M)this;
	}
	
	public String getTotal() {
		return getStr("total");
	}

	public M setJointime(java.util.Date jointime) {
		set("jointime", jointime);
		return (M)this;
	}
	
	public java.util.Date getJointime() {
		return get("jointime");
	}

}
