package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePileCard<M extends BasePileCard<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setDeviceId(Long deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public Long getDeviceId() {
		return getLong("deviceId");
	}

	public M setMsisdn(Long msisdn) {
		set("msisdn", msisdn);
		return (M)this;
	}
	
	public Long getMsisdn() {
		return getLong("msisdn");
	}

	public M setIccid(String iccid) {
		set("iccid", iccid);
		return (M)this;
	}
	
	public String getIccid() {
		return getStr("iccid");
	}

	public M setState(String state) {
		set("state", state);
		return (M)this;
	}
	
	public String getState() {
		return getStr("state");
	}

	public M setUser(Double user) {
		set("user", user);
		return (M)this;
	}
	
	public Double getUser() {
		return getDouble("user");
	}

	public M setTotal(Double total) {
		set("total", total);
		return (M)this;
	}
	
	public Double getTotal() {
		return getDouble("total");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
