package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceport<M extends BaseDeviceport<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
		return (M)this;
	}
	
	public java.lang.String getDeviceid() {
		return getStr("deviceid");
	}

	public M setPort(java.lang.String port) {
		set("port", port);
		return (M)this;
	}
	
	public java.lang.String getPort() {
		return getStr("port");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
		return (M)this;
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}

}
