package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTuserAndCoupon<M extends BaseTuserAndCoupon<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTuserId(java.lang.Long tuserId) {
		set("tuser_id", tuserId);
		return (M)this;
	}
	
	public java.lang.Long getTuserId() {
		return getLong("tuser_id");
	}

	public M setCouponId(java.lang.Long couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}
	
	public java.lang.Long getCouponId() {
		return getLong("coupon_id");
	}

	public M setCouponAmount(java.lang.Integer couponAmount) {
		set("coupon_amount", couponAmount);
		return (M)this;
	}
	
	public java.lang.Integer getCouponAmount() {
		return getInt("coupon_amount");
	}

}
