package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseElectricityMeter<M extends BaseElectricityMeter<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setCompanyId(Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public Long getCompanyId() {
		return getLong("company_id");
	}

	public M setProjectId(Long projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public Long getProjectId() {
		return getLong("project_id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}
	
	public String getType() {
		return getStr("type");
	}

	public M setPrice(Integer price) {
		set("price", price);
		return (M)this;
	}
	
	public Integer getPrice() {
		return getInt("price");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
