package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargeBatteryInfo<M extends BaseChargeBatteryInfo<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public String getOpenId() {
		return getStr("openId");
	}

	public M setDeviceId(String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public String getDeviceId() {
		return getStr("deviceId");
	}

	public M setDevicePort(String devicePort) {
		set("devicePort", devicePort);
		return (M)this;
	}
	
	public String getDevicePort() {
		return getStr("devicePort");
	}

	public M setOperStartTime(java.util.Date operStartTime) {
		set("operStartTime", operStartTime);
		return (M)this;
	}
	
	public java.util.Date getOperStartTime() {
		return get("operStartTime");
	}

	public M setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public M setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public M setFeeStatus(String feeStatus) {
		set("feeStatus", feeStatus);
		return (M)this;
	}
	
	public String getFeeStatus() {
		return getStr("feeStatus");
	}

	public M setOperType(String operType) {
		set("operType", operType);
		return (M)this;
	}
	
	public String getOperType() {
		return getStr("operType");
	}

	public M setServerResultCode(String serverResultCode) {
		set("serverResultCode", serverResultCode);
		return (M)this;
	}
	
	public String getServerResultCode() {
		return getStr("serverResultCode");
	}

	public M setServerResultDesc(String serverResultDesc) {
		set("serverResultDesc", serverResultDesc);
		return (M)this;
	}
	
	public String getServerResultDesc() {
		return getStr("serverResultDesc");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public M setCharge(String charge) {
		set("charge", charge);
		return (M)this;
	}
	
	public String getCharge() {
		return getStr("charge");
	}

	public M setWalletAccount(Integer walletAccount) {
		set("walletAccount", walletAccount);
		return (M)this;
	}
	
	public Integer getWalletAccount() {
		return getInt("walletAccount");
	}

	public M setChargeTime(String chargeTime) {
		set("chargeTime", chargeTime);
		return (M)this;
	}
	
	public String getChargeTime() {
		return getStr("chargeTime");
	}

	public M setRealChargeTime(String realChargeTime) {
		set("realChargeTime", realChargeTime);
		return (M)this;
	}
	
	public String getRealChargeTime() {
		return getStr("realChargeTime");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setMD5(String MD5) {
		set("MD5", MD5);
		return (M)this;
	}
	
	public String getMD5() {
		return getStr("MD5");
	}

	public M setPayToAgentStatus(String payToAgentStatus) {
		set("pay_to_agent_status", payToAgentStatus);
		return (M)this;
	}
	
	public String getPayToAgentStatus() {
		return getStr("pay_to_agent_status");
	}

	public M setAutoCharge(String autoCharge) {
		set("auto_charge", autoCharge);
		return (M)this;
	}
	
	public String getAutoCharge() {
		return getStr("auto_charge");
	}

	public M setPayToAgentTime(java.util.Date payToAgentTime) {
		set("pay_to_agent_time", payToAgentTime);
		return (M)this;
	}
	
	public java.util.Date getPayToAgentTime() {
		return get("pay_to_agent_time");
	}

	public M setAddMoney(String addMoney) {
		set("add_money", addMoney);
		return (M)this;
	}
	
	public String getAddMoney() {
		return getStr("add_money");
	}

}
