package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMoneyMatchActivity<M extends BaseMoneyMatchActivity<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setActNum(String actNum) {
		set("actNum", actNum);
		return (M)this;
	}
	
	public String getActNum() {
		return getStr("actNum");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}
	
	public String getType() {
		return getStr("type");
	}

	public M setMoney(Double money) {
		set("money", money);
		return (M)this;
	}
	
	public Double getMoney() {
		return getDouble("money");
	}

	public M setChargeNum(Integer chargeNum) {
		set("chargeNum", chargeNum);
		return (M)this;
	}
	
	public Integer getChargeNum() {
		return getInt("chargeNum");
	}

	public M setCoupon(Integer coupon) {
		set("coupon", coupon);
		return (M)this;
	}
	
	public Integer getCoupon() {
		return getInt("coupon");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public M setTime(String time) {
		set("time", time);
		return (M)this;
	}
	
	public String getTime() {
		return getStr("time");
	}

	public M setActivityId(Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}
	
	public Integer getActivityId() {
		return getInt("activity_id");
	}

	public M setArea(String area) {
		set("area", area);
		return (M)this;
	}
	
	public String getArea() {
		return getStr("area");
	}

}
