package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeixinToken<M extends BaseWeixinToken<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("accessToken", accessToken);
		return (M)this;
	}
	
	public java.lang.String getAccessToken() {
		return getStr("accessToken");
	}

	public M setJsapiTicket(java.lang.String jsapiTicket) {
		set("jsapiTicket", jsapiTicket);
		return (M)this;
	}
	
	public java.lang.String getJsapiTicket() {
		return getStr("jsapiTicket");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
