package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAppid(java.lang.String appid) {
		set("appid", appid);
		return (M)this;
	}
	
	public java.lang.String getAppid() {
		return getStr("appid");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
		return (M)this;
	}
	
	public java.lang.String getOutTradeNo() {
		return getStr("out_trade_no");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
		return (M)this;
	}
	
	public java.lang.String getMchId() {
		return getStr("mch_id");
	}

	public M setCashFee(java.lang.Integer cashFee) {
		set("cash_fee", cashFee);
		return (M)this;
	}
	
	public java.lang.Integer getCashFee() {
		return getInt("cash_fee");
	}

	public M setTotalFee(java.lang.Integer totalFee) {
		set("total_fee", totalFee);
		return (M)this;
	}
	
	public java.lang.Integer getTotalFee() {
		return getInt("total_fee");
	}

	public M setFeeType(java.lang.String feeType) {
		set("fee_type", feeType);
		return (M)this;
	}
	
	public java.lang.String getFeeType() {
		return getStr("fee_type");
	}

	public M setResultCode(java.lang.String resultCode) {
		set("result_code", resultCode);
		return (M)this;
	}
	
	public java.lang.String getResultCode() {
		return getStr("result_code");
	}

	public M setErrCode(java.lang.String errCode) {
		set("err_code", errCode);
		return (M)this;
	}
	
	public java.lang.String getErrCode() {
		return getStr("err_code");
	}

	public M setErrCodeDes(java.lang.String errCodeDes) {
		set("err_code_des", errCodeDes);
		return (M)this;
	}
	
	public java.lang.String getErrCodeDes() {
		return getStr("err_code_des");
	}

	public M setIsSubscribe(java.lang.String isSubscribe) {
		set("is_subscribe", isSubscribe);
		return (M)this;
	}
	
	public java.lang.String getIsSubscribe() {
		return getStr("is_subscribe");
	}

	public M setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
		return (M)this;
	}
	
	public java.lang.String getTradeType() {
		return getStr("trade_type");
	}

	public M setBankType(java.lang.String bankType) {
		set("bank_type", bankType);
		return (M)this;
	}
	
	public java.lang.String getBankType() {
		return getStr("bank_type");
	}

	public M setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
		return (M)this;
	}
	
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	public M setCouponId(java.lang.String couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}
	
	public java.lang.String getCouponId() {
		return getStr("coupon_id");
	}

	public M setCouponFee(java.lang.Integer couponFee) {
		set("coupon_fee", couponFee);
		return (M)this;
	}
	
	public java.lang.Integer getCouponFee() {
		return getInt("coupon_fee");
	}

	public M setCouponCount(java.lang.Integer couponCount) {
		set("coupon_count", couponCount);
		return (M)this;
	}
	
	public java.lang.Integer getCouponCount() {
		return getInt("coupon_count");
	}

	public M setAttach(java.lang.String attach) {
		set("attach", attach);
		return (M)this;
	}
	
	public java.lang.String getAttach() {
		return getStr("attach");
	}

	public M setTimeEnd(java.lang.String timeEnd) {
		set("time_end", timeEnd);
		return (M)this;
	}
	
	public java.lang.String getTimeEnd() {
		return getStr("time_end");
	}

	public M setCouresCount(java.lang.Integer couresCount) {
		set("couresCount", couresCount);
		return (M)this;
	}
	
	public java.lang.Integer getCouresCount() {
		return getInt("couresCount");
	}

	public M setCouresId(java.lang.Integer couresId) {
		set("couresId", couresId);
		return (M)this;
	}
	
	public java.lang.Integer getCouresId() {
		return getInt("couresId");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
