package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargePile<M extends BaseChargePile<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setProvince(String province) {
		set("province", province);
		return (M)this;
	}
	
	public String getProvince() {
		return getStr("province");
	}

	public M setCity(String city) {
		set("city", city);
		return (M)this;
	}
	
	public String getCity() {
		return getStr("city");
	}

	public M setDetailLocation(String detailLocation) {
		set("detail_location", detailLocation);
		return (M)this;
	}
	
	public String getDetailLocation() {
		return getStr("detail_location");
	}

	public M setLat(Double lat) {
		set("lat", lat);
		return (M)this;
	}
	
	public Double getLat() {
		return getDouble("lat");
	}

	public M setLng(Double lng) {
		set("lng", lng);
		return (M)this;
	}
	
	public Double getLng() {
		return getDouble("lng");
	}

	public M setSocketNumber(Integer socketNumber) {
		set("socket_number", socketNumber);
		return (M)this;
	}
	
	public Integer getSocketNumber() {
		return getInt("socket_number");
	}

	public M setTotalIntensity(Double totalIntensity) {
		set("total_intensity", totalIntensity);
		return (M)this;
	}
	
	public Double getTotalIntensity() {
		return getDouble("total_intensity");
	}

	public M setTotalVoltage(Double totalVoltage) {
		set("total_voltage", totalVoltage);
		return (M)this;
	}
	
	public Double getTotalVoltage() {
		return getDouble("total_voltage");
	}

	public M setIsOnline(Boolean isOnline) {
		set("is_online", isOnline);
		return (M)this;
	}
	
	public Boolean getIsOnline() {
		return get("is_online");
	}

	public M setOnlineDate(java.util.Date onlineDate) {
		set("online_date", onlineDate);
		return (M)this;
	}
	
	public java.util.Date getOnlineDate() {
		return get("online_date");
	}

	public M setUpdateTime(Long updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public Long getUpdateTime() {
		return getLong("update_time");
	}

}
