package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrMatchDevice<M extends BaseQrMatchDevice<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setGid(Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public Integer getGid() {
		return getInt("gid");
	}

	public M setGname(String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public String getGname() {
		return getStr("gname");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}
	
	public String getType() {
		return getStr("type");
	}

	public M setQrNum(String qrNum) {
		set("qr_num", qrNum);
		return (M)this;
	}
	
	public String getQrNum() {
		return getStr("qr_num");
	}

	public M setMatchNum(String matchNum) {
		set("match_num", matchNum);
		return (M)this;
	}
	
	public String getMatchNum() {
		return getStr("match_num");
	}

	public M setArea(String area) {
		set("area", area);
		return (M)this;
	}
	
	public String getArea() {
		return getStr("area");
	}

	public M setTowHoursPrice(Integer towHoursPrice) {
		set("tow_hours_price", towHoursPrice);
		return (M)this;
	}
	
	public Integer getTowHoursPrice() {
		return getInt("tow_hours_price");
	}

	public M setFourHoursPrice(Integer fourHoursPrice) {
		set("four_hours_price", fourHoursPrice);
		return (M)this;
	}
	
	public Integer getFourHoursPrice() {
		return getInt("four_hours_price");
	}

	public M setEightHoursPrice(Integer eightHoursPrice) {
		set("eight_hours_price", eightHoursPrice);
		return (M)this;
	}
	
	public Integer getEightHoursPrice() {
		return getInt("eight_hours_price");
	}

	public M setTwelveHoursPrice(Integer twelveHoursPrice) {
		set("twelve_hours_price", twelveHoursPrice);
		return (M)this;
	}
	
	public Integer getTwelveHoursPrice() {
		return getInt("twelve_hours_price");
	}

	public M setTowHoursMemPrice(Integer towHoursMemPrice) {
		set("tow_hours_mem_price", towHoursMemPrice);
		return (M)this;
	}
	
	public Integer getTowHoursMemPrice() {
		return getInt("tow_hours_mem_price");
	}

	public M setFourHoursMemPrice(Integer fourHoursMemPrice) {
		set("four_hours_mem_price", fourHoursMemPrice);
		return (M)this;
	}
	
	public Integer getFourHoursMemPrice() {
		return getInt("four_hours_mem_price");
	}

	public M setEightHoursMemPrice(Integer eightHoursMemPrice) {
		set("eight_hours_mem_price", eightHoursMemPrice);
		return (M)this;
	}
	
	public Integer getEightHoursMemPrice() {
		return getInt("eight_hours_mem_price");
	}

	public M setTwelveHoursMemPrice(Integer twelveHoursMemPrice) {
		set("twelve_hours_mem_price", twelveHoursMemPrice);
		return (M)this;
	}
	
	public Integer getTwelveHoursMemPrice() {
		return getInt("twelve_hours_mem_price");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setAutoPrice(Integer autoPrice) {
		set("auto_price", autoPrice);
		return (M)this;
	}
	
	public Integer getAutoPrice() {
		return getInt("auto_price");
	}

	public M setPowerA1(String powerA1) {
		set("power_a1", powerA1);
		return (M)this;
	}
	
	public String getPowerA1() {
		return getStr("power_a1");
	}

	public M setPowerA2(String powerA2) {
		set("power_a2", powerA2);
		return (M)this;
	}
	
	public String getPowerA2() {
		return getStr("power_a2");
	}

	public M setPowerA3(String powerA3) {
		set("power_a3", powerA3);
		return (M)this;
	}
	
	public String getPowerA3() {
		return getStr("power_a3");
	}

	public M setPowerA4(String powerA4) {
		set("power_a4", powerA4);
		return (M)this;
	}
	
	public String getPowerA4() {
		return getStr("power_a4");
	}

	public M setPowerA5(String powerA5) {
		set("power_a5", powerA5);
		return (M)this;
	}
	
	public String getPowerA5() {
		return getStr("power_a5");
	}

	public M setPowerA6(String powerA6) {
		set("power_a6", powerA6);
		return (M)this;
	}
	
	public String getPowerA6() {
		return getStr("power_a6");
	}

	public M setPowerA7(String powerA7) {
		set("power_a7", powerA7);
		return (M)this;
	}
	
	public String getPowerA7() {
		return getStr("power_a7");
	}

	public M setActivityId(Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}
	
	public Integer getActivityId() {
		return getInt("activity_id");
	}

	public M setFree(String free) {
		set("free", free);
		return (M)this;
	}
	
	public String getFree() {
		return getStr("free");
	}

	public M setPayToAgentStatus(String payToAgentStatus) {
		set("pay_to_agent_status", payToAgentStatus);
		return (M)this;
	}
	
	public String getPayToAgentStatus() {
		return getStr("pay_to_agent_status");
	}

	public M setPayToAgentOpenid(String payToAgentOpenid) {
		set("pay_to_agent_openid", payToAgentOpenid);
		return (M)this;
	}
	
	public String getPayToAgentOpenid() {
		return getStr("pay_to_agent_openid");
	}

	public M setPayToAgentName(String payToAgentName) {
		set("pay_to_agent_name", payToAgentName);
		return (M)this;
	}
	
	public String getPayToAgentName() {
		return getStr("pay_to_agent_name");
	}

}
