package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDroppedlog<M extends BaseDroppedlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
		return (M)this;
	}
	
	public java.lang.String getDeviceid() {
		return getStr("deviceid");
	}

	public M setErcode(java.lang.String ercode) {
		set("ercode", ercode);
		return (M)this;
	}
	
	public java.lang.String getErcode() {
		return getStr("ercode");
	}

	public M setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
		return (M)this;
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}

	public M setReson(java.lang.String reson) {
		set("reson", reson);
		return (M)this;
	}
	
	public java.lang.String getReson() {
		return getStr("reson");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
