package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
		return (M)this;
	}
	
	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public M setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
		return (M)this;
	}
	
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	public M setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	public M setAdminTel(java.lang.String adminTel) {
		set("admin_tel", adminTel);
		return (M)this;
	}
	
	public java.lang.String getAdminTel() {
		return getStr("admin_tel");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setTowHoursPrice(java.lang.Integer towHoursPrice) {
		set("tow_hours_price", towHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTowHoursPrice() {
		return getInt("tow_hours_price");
	}

	public M setFourHoursPrice(java.lang.Integer fourHoursPrice) {
		set("four_hours_price", fourHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getFourHoursPrice() {
		return getInt("four_hours_price");
	}

	public M setEightHoursPrice(java.lang.Integer eightHoursPrice) {
		set("eight_hours_price", eightHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getEightHoursPrice() {
		return getInt("eight_hours_price");
	}

	public M setTwelveHoursPrice(java.lang.Integer twelveHoursPrice) {
		set("twelve_hours_price", twelveHoursPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTwelveHoursPrice() {
		return getInt("twelve_hours_price");
	}

	public M setTowHoursMemPrice(java.lang.Integer towHoursMemPrice) {
		set("tow_hours_mem_price", towHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTowHoursMemPrice() {
		return getInt("tow_hours_mem_price");
	}

	public M setFourHoursMemPrice(java.lang.Integer fourHoursMemPrice) {
		set("four_hours_mem_price", fourHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getFourHoursMemPrice() {
		return getInt("four_hours_mem_price");
	}

	public M setEightHoursMemPrice(java.lang.Integer eightHoursMemPrice) {
		set("eight_hours_mem_price", eightHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getEightHoursMemPrice() {
		return getInt("eight_hours_mem_price");
	}

	public M setTwelveHoursMemPrice(java.lang.Integer twelveHoursMemPrice) {
		set("twelve_hours_mem_price", twelveHoursMemPrice);
		return (M)this;
	}
	
	public java.lang.Integer getTwelveHoursMemPrice() {
		return getInt("twelve_hours_mem_price");
	}

	public M setAutoPrice(java.lang.Integer autoPrice) {
		set("auto_price", autoPrice);
		return (M)this;
	}
	
	public java.lang.Integer getAutoPrice() {
		return getInt("auto_price");
	}

	public M setAutoUnitPrice(java.lang.Integer autoUnitPrice) {
		set("auto_unit_price", autoUnitPrice);
		return (M)this;
	}
	
	public java.lang.Integer getAutoUnitPrice() {
		return getInt("auto_unit_price");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setPowerA1(java.lang.Integer powerA1) {
		set("power_a1", powerA1);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA1() {
		return getInt("power_a1");
	}

	public M setPowerA2(java.lang.Integer powerA2) {
		set("power_a2", powerA2);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA2() {
		return getInt("power_a2");
	}

	public M setPowerA3(java.lang.Integer powerA3) {
		set("power_a3", powerA3);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA3() {
		return getInt("power_a3");
	}

	public M setPowerA4(java.lang.Integer powerA4) {
		set("power_a4", powerA4);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA4() {
		return getInt("power_a4");
	}

	public M setPowerA5(java.lang.Integer powerA5) {
		set("power_a5", powerA5);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA5() {
		return getInt("power_a5");
	}

	public M setPowerA6(java.lang.Integer powerA6) {
		set("power_a6", powerA6);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA6() {
		return getInt("power_a6");
	}

	public M setPowerA7(java.lang.Integer powerA7) {
		set("power_a7", powerA7);
		return (M)this;
	}
	
	public java.lang.Integer getPowerA7() {
		return getInt("power_a7");
	}

	public M setFree(java.lang.String free) {
		set("free", free);
		return (M)this;
	}
	
	public java.lang.String getFree() {
		return getStr("free");
	}

}
