package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
		return (M)this;
	}
	
	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public M setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
		return (M)this;
	}
	
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	public M setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	public M setAdminTel(java.lang.String adminTel) {
		set("admin_tel", adminTel);
		return (M)this;
	}
	
	public java.lang.String getAdminTel() {
		return getStr("admin_tel");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

}
