package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTuser<M extends BaseTuser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}
	
	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public M setPrivilege(java.lang.String privilege) {
		set("privilege", privilege);
		return (M)this;
	}
	
	public java.lang.String getPrivilege() {
		return getStr("privilege");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setPassword2(java.lang.String password2) {
		set("password2", password2);
		return (M)this;
	}
	
	public java.lang.String getPassword2() {
		return getStr("password2");
	}

	public M setRemember(java.lang.String remember) {
		set("remember", remember);
		return (M)this;
	}
	
	public java.lang.String getRemember() {
		return getStr("remember");
	}

	public M setRegisterDate(java.util.Date registerDate) {
		set("registerDate", registerDate);
		return (M)this;
	}
	
	public java.util.Date getRegisterDate() {
		return get("registerDate");
	}

	public M setLastLoginDate(java.util.Date lastLoginDate) {
		set("lastLoginDate", lastLoginDate);
		return (M)this;
	}
	
	public java.util.Date getLastLoginDate() {
		return get("lastLoginDate");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setCardNumber(java.lang.String cardNumber) {
		set("cardNumber", cardNumber);
		return (M)this;
	}
	
	public java.lang.String getCardNumber() {
		return getStr("cardNumber");
	}

	public M setPhyCardNumber(java.lang.String phyCardNumber) {
		set("phyCardNumber", phyCardNumber);
		return (M)this;
	}
	
	public java.lang.String getPhyCardNumber() {
		return getStr("phyCardNumber");
	}

	public M setCardAccount(java.lang.Integer cardAccount) {
		set("cardAccount", cardAccount);
		return (M)this;
	}
	
	public java.lang.Integer getCardAccount() {
		return getInt("cardAccount");
	}

	public M setBand(java.lang.String band) {
		set("band", band);
		return (M)this;
	}
	
	public java.lang.String getBand() {
		return getStr("band");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setWalletNumber(java.lang.String walletNumber) {
		set("walletNumber", walletNumber);
		return (M)this;
	}
	
	public java.lang.String getWalletNumber() {
		return getStr("walletNumber");
	}

	public M setWalletAccount(java.lang.Integer walletAccount) {
		set("walletAccount", walletAccount);
		return (M)this;
	}
	
	public java.lang.Integer getWalletAccount() {
		return getInt("walletAccount");
	}

	public M setWalletRealMoney(java.lang.Integer walletRealMoney) {
		set("wallet_real_money", walletRealMoney);
		return (M)this;
	}
	
	public java.lang.Integer getWalletRealMoney() {
		return getInt("wallet_real_money");
	}

	public M setWalletGiftMoney(java.lang.Integer walletGiftMoney) {
		set("wallet_gift_money", walletGiftMoney);
		return (M)this;
	}
	
	public java.lang.Integer getWalletGiftMoney() {
		return getInt("wallet_gift_money");
	}

	public M setRealGitRate(java.lang.Double realGitRate) {
		set("real_git_rate", realGitRate);
		return (M)this;
	}
	
	public java.lang.Double getRealGitRate() {
		return getDouble("real_git_rate");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setProxyWalletRealMoney(java.lang.Integer proxyWalletRealMoney) {
		set("proxy_wallet_real_money", proxyWalletRealMoney);
		return (M)this;
	}
	
	public java.lang.Integer getProxyWalletRealMoney() {
		return getInt("proxy_wallet_real_money");
	}

	public M setProxyWalletGiftMoney(java.lang.Integer proxyWalletGiftMoney) {
		set("proxy_wallet_gift_money", proxyWalletGiftMoney);
		return (M)this;
	}
	
	public java.lang.Integer getProxyWalletGiftMoney() {
		return getInt("proxy_wallet_gift_money");
	}

	public M setProxyRealGitRate(java.lang.Double proxyRealGitRate) {
		set("proxy_real_git_rate", proxyRealGitRate);
		return (M)this;
	}
	
	public java.lang.Double getProxyRealGitRate() {
		return getDouble("proxy_real_git_rate");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
		return (M)this;
	}
	
	public java.lang.Integer getRole() {
		return getInt("role");
	}

}
