package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSendWeixinMessage<M extends BaseSendWeixinMessage<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public String getOpenId() {
		return getStr("openId");
	}

	public M setDeviceId(String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public String getDeviceId() {
		return getStr("deviceId");
	}

	public M setSocket(String socket) {
		set("socket", socket);
		return (M)this;
	}
	
	public String getSocket() {
		return getStr("socket");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}
	
	public String getContent() {
		return getStr("content");
	}

	public M setResult(String result) {
		set("result", result);
		return (M)this;
	}
	
	public String getResult() {
		return getStr("result");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
