package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBMap<M extends BaseBMap<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}
	
	public String getDeviceId() {
		return getStr("device_id");
	}

	public M setEPoint(Double ePoint) {
		set("e_point", ePoint);
		return (M)this;
	}
	
	public Double getEPoint() {
		return getDouble("e_point");
	}

	public M setNPoint(Double nPoint) {
		set("n_point", nPoint);
		return (M)this;
	}
	
	public Double getNPoint() {
		return getDouble("n_point");
	}

	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public M setTel(String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public String getTel() {
		return getStr("tel");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
