package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setGname(String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public String getGname() {
		return getStr("gname");
	}

	public M setGid(Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public Integer getGid() {
		return getInt("gid");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public String getPhone() {
		return getStr("phone");
	}

	public M setCardnum(String cardnum) {
		set("cardnum", cardnum);
		return (M)this;
	}
	
	public String getCardnum() {
		return getStr("cardnum");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public M setMoney(String money) {
		set("money", money);
		return (M)this;
	}
	
	public String getMoney() {
		return getStr("money");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public Integer getStatus() {
		return getInt("status");
	}

	public M setTotal(String total) {
		set("total", total);
		return (M)this;
	}
	
	public String getTotal() {
		return getStr("total");
	}

}
