package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargeHistory<M extends BaseRechargeHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setMoneySum(java.lang.Integer moneySum) {
		set("money_sum", moneySum);
		return (M)this;
	}
	
	public java.lang.Integer getMoneySum() {
		return getInt("money_sum");
	}

	public M setRealMoney(java.lang.Integer realMoney) {
		set("real_money", realMoney);
		return (M)this;
	}
	
	public java.lang.Integer getRealMoney() {
		return getInt("real_money");
	}

	public M setCoupon(java.lang.Integer coupon) {
		set("coupon", coupon);
		return (M)this;
	}
	
	public java.lang.Integer getCoupon() {
		return getInt("coupon");
	}

	public M setPayAgentStatus(java.lang.Integer payAgentStatus) {
		set("pay_agent_status", payAgentStatus);
		return (M)this;
	}
	
	public java.lang.Integer getPayAgentStatus() {
		return getInt("pay_agent_status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setRechargeTime(java.util.Date rechargeTime) {
		set("recharge_time", rechargeTime);
		return (M)this;
	}
	
	public java.util.Date getRechargeTime() {
		return get("recharge_time");
	}

	public M setPayAgentTime(java.util.Date payAgentTime) {
		set("payAgentTime", payAgentTime);
		return (M)this;
	}
	
	public java.util.Date getPayAgentTime() {
		return get("payAgentTime");
	}

}
