package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setGname(java.lang.String gname) {
		set("gname", gname);
		return (M)this;
	}
	
	public java.lang.String getGname() {
		return getStr("gname");
	}

	public M setGid(java.lang.Integer gid) {
		set("gid", gid);
		return (M)this;
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setCardnum(java.lang.String cardnum) {
		set("cardnum", cardnum);
		return (M)this;
	}
	
	public java.lang.String getCardnum() {
		return getStr("cardnum");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setMoney(java.lang.String money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.String getMoney() {
		return getStr("money");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setTotal(java.lang.String total) {
		set("total", total);
		return (M)this;
	}
	
	public java.lang.String getTotal() {
		return getStr("total");
	}

}
