package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setTaxpayerId(java.lang.String taxpayerId) {
		set("taxpayer_id", taxpayerId);
		return (M)this;
	}
	
	public java.lang.String getTaxpayerId() {
		return getStr("taxpayer_id");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setDetailLocation(java.lang.String detailLocation) {
		set("detail_location", detailLocation);
		return (M)this;
	}
	
	public java.lang.String getDetailLocation() {
		return getStr("detail_location");
	}

	public M setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
		return (M)this;
	}
	
	public java.lang.String getLegalPerson() {
		return getStr("legal_person");
	}

	public M setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
		return (M)this;
	}
	
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	public M setBalanceRate(java.lang.Double balanceRate) {
		set("balance_rate", balanceRate);
		return (M)this;
	}
	
	public java.lang.Double getBalanceRate() {
		return getDouble("balance_rate");
	}

	public M setBalanceType(java.lang.Integer balanceType) {
		set("balance_type", balanceType);
		return (M)this;
	}
	
	public java.lang.Integer getBalanceType() {
		return getInt("balance_type");
	}

	public M setWeixinAccount(java.lang.String weixinAccount) {
		set("weixin_account", weixinAccount);
		return (M)this;
	}
	
	public java.lang.String getWeixinAccount() {
		return getStr("weixin_account");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public M setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
		return (M)this;
	}
	
	public java.lang.String getContactPhone() {
		return getStr("contact_phone");
	}

}
