package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseElectricityMeterHistory<M extends BaseElectricityMeterHistory<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setMeterId(Long meterId) {
		set("meter_id", meterId);
		return (M)this;
	}
	
	public Long getMeterId() {
		return getLong("meter_id");
	}

	public M setLastNum(Double lastNum) {
		set("last_num", lastNum);
		return (M)this;
	}
	
	public Double getLastNum() {
		return getDouble("last_num");
	}

	public M setCurrNum(Double currNum) {
		set("curr_num", currNum);
		return (M)this;
	}
	
	public Double getCurrNum() {
		return getDouble("curr_num");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public String getOpenId() {
		return getStr("openId");
	}

	public M setCount(Double count) {
		set("count", count);
		return (M)this;
	}
	
	public Double getCount() {
		return getDouble("count");
	}

	public M setTotal(Double total) {
		set("total", total);
		return (M)this;
	}
	
	public Double getTotal() {
		return getDouble("total");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCurrDate(java.util.Date currDate) {
		set("curr_date", currDate);
		return (M)this;
	}
	
	public java.util.Date getCurrDate() {
		return get("curr_date");
	}

}
