package net.inconnection.charge.extend.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMoneyMatchActivity<M extends BaseMoneyMatchActivity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setActNum(java.lang.String actNum) {
		set("actNum", actNum);
		return (M)this;
	}
	
	public java.lang.String getActNum() {
		return getStr("actNum");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setMoney(java.lang.Double money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.Double getMoney() {
		return getDouble("money");
	}

	public M setChargeNum(java.lang.Integer chargeNum) {
		set("chargeNum", chargeNum);
		return (M)this;
	}
	
	public java.lang.Integer getChargeNum() {
		return getInt("chargeNum");
	}

	public M setCoupon(java.lang.Integer coupon) {
		set("coupon", coupon);
		return (M)this;
	}
	
	public java.lang.Integer getCoupon() {
		return getInt("coupon");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}
	
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

}
