package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenuBtn<M extends BaseSysMenuBtn<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return get("menu_id");
	}

	public M setBtnName(String btnName) {
		set("btn_name", btnName);
		return (M)this;
	}

	public String getBtnName() {
		return get("btn_name");
	}

	public M setClassName(String className) {
		set("class_name", className);
		return (M)this;
	}

	public String getClassName() {
		return get("class_name");
	}

	public M setMethodName(String methodName) {
		set("method_name", methodName);
		return (M)this;
	}

	public String getMethodName() {
		return get("method_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
