package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommonFile<M extends BaseCommonFile<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return get("type");
	}

	public M setPath(String path) {
		set("path", path);
		return (M)this;
	}

	public String getPath() {
		return get("path");
	}

	public M setSysUserId(Integer sysUserId) {
		set("sys_user_id", sysUserId);
		return (M)this;
	}

	public Integer getSysUserId() {
		return get("sys_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
