package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRoleMenu<M extends BaseSysRoleMenu<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setRoleId(Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Integer getRoleId() {
		return get("role_id");
	}

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return get("menu_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
