package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskLog<M extends BaseTaskLog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setTaskId(Integer taskId) {
		set("task_id", taskId);
		return (M)this;
	}

	public Integer getTaskId() {
		return get("task_id");
	}

	public M setResult(String result) {
		set("result", result);
		return (M)this;
	}

	public String getResult() {
		return get("result");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setCostTime(Integer costTime) {
		set("cost_time", costTime);
		return (M)this;
	}

	public Integer getCostTime() {
		return get("cost_time");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

}
