package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDictType(String dictType) {
		set("dict_type", dictType);
		return (M)this;
	}

	public String getDictType() {
		return get("dict_type");
	}

	public M setDictKey(String dictKey) {
		set("dict_key", dictKey);
		return (M)this;
	}

	public String getDictKey() {
		return get("dict_key");
	}

	public M setDictValue(String dictValue) {
		set("dict_value", dictValue);
		return (M)this;
	}

	public String getDictValue() {
		return get("dict_value");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
