package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdField<M extends BaseZcurdField<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setHeadId(Integer headId) {
		set("head_id", headId);
		return (M)this;
	}

	public Integer getHeadId() {
		return get("head_id");
	}

	public M setFieldName(String fieldName) {
		set("field_name", fieldName);
		return (M)this;
	}

	public String getFieldName() {
		return get("field_name");
	}

	public M setColumnName(String columnName) {
		set("column_name", columnName);
		return (M)this;
	}

	public String getColumnName() {
		return get("column_name");
	}

	public M setColumnLength(Integer columnLength) {
		set("column_length", columnLength);
		return (M)this;
	}

	public Integer getColumnLength() {
		return get("column_length");
	}

	public M setDataType(String dataType) {
		set("data_type", dataType);
		return (M)this;
	}

	public String getDataType() {
		return get("data_type");
	}

	public M setInputType(String inputType) {
		set("input_type", inputType);
		return (M)this;
	}

	public String getInputType() {
		return get("input_type");
	}

	public M setIsShowList(Integer isShowList) {
		set("is_show_list", isShowList);
		return (M)this;
	}

	public Integer getIsShowList() {
		return get("is_show_list");
	}

	public M setIsAllowDetail(Integer isAllowDetail) {
		set("is_allow_detail", isAllowDetail);
		return (M)this;
	}

	public Integer getIsAllowDetail() {
		return get("is_allow_detail");
	}

	public M setIsAllowAdd(Integer isAllowAdd) {
		set("is_allow_add", isAllowAdd);
		return (M)this;
	}

	public Integer getIsAllowAdd() {
		return get("is_allow_add");
	}

	public M setIsAllowUpdate(Integer isAllowUpdate) {
		set("is_allow_update", isAllowUpdate);
		return (M)this;
	}

	public Integer getIsAllowUpdate() {
		return get("is_allow_update");
	}

	public M setIsSearch(Integer isSearch) {
		set("is_search", isSearch);
		return (M)this;
	}

	public Integer getIsSearch() {
		return get("is_search");
	}

	public M setIsAllowNull(Integer isAllowNull) {
		set("is_allow_null", isAllowNull);
		return (M)this;
	}

	public Integer getIsAllowNull() {
		return get("is_allow_null");
	}

	public M setDictSql(String dictSql) {
		set("dict_sql", dictSql);
		return (M)this;
	}

	public String getDictSql() {
		return get("dict_sql");
	}

	public M setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public Integer getOrderNum() {
		return get("order_num");
	}

	public M setSearchType(Integer searchType) {
		set("search_type", searchType);
		return (M)this;
	}

	public Integer getSearchType() {
		return get("search_type");
	}

	public M setIsSum(Integer isSum) {
		set("is_sum", isSum);
		return (M)this;
	}

	public Integer getIsSum() {
		return get("is_sum");
	}

	public M setDefaultValue(String defaultValue) {
		set("default_value", defaultValue);
		return (M)this;
	}

	public String getDefaultValue() {
		return get("default_value");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
