package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdHeadJs<M extends BaseZcurdHeadJs<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setHeadId(Integer headId) {
		set("head_id", headId);
		return (M)this;
	}

	public Integer getHeadId() {
		return get("head_id");
	}

	public M setPage(String page) {
		set("page", page);
		return (M)this;
	}

	public String getPage() {
		return get("page");
	}

	public M setSqlContent(String sqlContent) {
		set("sql_content", sqlContent);
		return (M)this;
	}

	public String getSqlContent() {
		return get("sql_content");
	}

	public M setJsContent(String jsContent) {
		set("js_content", jsContent);
		return (M)this;
	}

	public String getJsContent() {
		return get("js_content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
