package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbProcLog<M extends BaseTbProcLog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setProcName(String procName) {
		set("proc_name", procName);
		return (M)this;
	}

	public String getProcName() {
		return get("proc_name");
	}

	public M setStatu(String statu) {
		set("statu", statu);
		return (M)this;
	}

	public String getStatu() {
		return get("statu");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setCostTime(Integer costTime) {
		set("cost_time", costTime);
		return (M)this;
	}

	public Integer getCostTime() {
		return get("cost_time");
	}

	public M setErrorCode(String errorCode) {
		set("error_code", errorCode);
		return (M)this;
	}

	public String getErrorCode() {
		return get("error_code");
	}

	public M setErrorMsg(String errorMsg) {
		set("error_msg", errorMsg);
		return (M)this;
	}

	public String getErrorMsg() {
		return get("error_msg");
	}

	public M setStep(Integer step) {
		set("step", step);
		return (M)this;
	}

	public Integer getStep() {
		return get("step");
	}

}
