package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdHead<M extends BaseZcurdHead<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setTableName(String tableName) {
		set("table_name", tableName);
		return (M)this;
	}

	public String getTableName() {
		return get("table_name");
	}

	public M setFormName(String formName) {
		set("form_name", formName);
		return (M)this;
	}

	public String getFormName() {
		return get("form_name");
	}

	public M setIdField(String idField) {
		set("id_field", idField);
		return (M)this;
	}

	public String getIdField() {
		return get("id_field");
	}

	public M setIsAuto(Integer isAuto) {
		set("is_auto", isAuto);
		return (M)this;
	}

	public Integer getIsAuto() {
		return get("is_auto");
	}

	public M setFormType(Integer formType) {
		set("form_type", formType);
		return (M)this;
	}

	public Integer getFormType() {
		return get("form_type");
	}

	public M setDialogSize(String dialogSize) {
		set("dialog_size", dialogSize);
		return (M)this;
	}

	public String getDialogSize() {
		return get("dialog_size");
	}

	public M setDbSource(String dbSource) {
		set("db_source", dbSource);
		return (M)this;
	}

	public String getDbSource() {
		return get("db_source");
	}

	public M setHandleClass(String handleClass) {
		set("handle_class", handleClass);
		return (M)this;
	}

	public String getHandleClass() {
		return get("handle_class");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
