package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOplog<M extends BaseSysOplog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return get("user_id");
	}

	public M setOpContent(String opContent) {
		set("op_content", opContent);
		return (M)this;
	}

	public String getOpContent() {
		return get("op_content");
	}

	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}

	public String getIp() {
		return get("ip");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
