package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZcurdHeadBtn<M extends BaseZcurdHeadBtn<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setHeadId(Integer headId) {
		set("head_id", headId);
		return (M)this;
	}

	public Integer getHeadId() {
		return get("head_id");
	}

	public M setBtnName(String btnName) {
		set("btn_name", btnName);
		return (M)this;
	}

	public String getBtnName() {
		return get("btn_name");
	}

	public M setBtnIcon(String btnIcon) {
		set("btn_icon", btnIcon);
		return (M)this;
	}

	public String getBtnIcon() {
		return get("btn_icon");
	}

	public M setLocation(Integer location) {
		set("location", location);
		return (M)this;
	}

	public Integer getLocation() {
		return get("location");
	}

	public M setAction(Integer action) {
		set("action", action);
		return (M)this;
	}

	public Integer getAction() {
		return get("action");
	}

	public M setFuncContent(String funcContent) {
		set("func_content", funcContent);
		return (M)this;
	}

	public String getFuncContent() {
		return get("func_content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
