package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskBase<M extends BaseTaskBase<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return get("name");
	}

	public M setTargetType(Integer targetType) {
		set("target_type", targetType);
		return (M)this;
	}

	public Integer getTargetType() {
		return get("target_type");
	}

	public M setTargetValue(String targetValue) {
		set("target_value", targetValue);
		return (M)this;
	}

	public String getTargetValue() {
		return get("target_value");
	}

	public M setCron(String cron) {
		set("cron", cron);
		return (M)this;
	}

	public String getCron() {
		return get("cron");
	}

	public M setLastRunResult(String lastRunResult) {
		set("last_run_result", lastRunResult);
		return (M)this;
	}

	public String getLastRunResult() {
		return get("last_run_result");
	}

	public M setLastRunTime(java.util.Date lastRunTime) {
		set("last_run_time", lastRunTime);
		return (M)this;
	}

	public java.util.Date getLastRunTime() {
		return get("last_run_time");
	}

	public M setLastRunTimeCost(Integer lastRunTimeCost) {
		set("last_run_time_cost", lastRunTimeCost);
		return (M)this;
	}

	public Integer getLastRunTimeCost() {
		return get("last_run_time_cost");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return get("status");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return get("create_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
