package net.inconnection.charge.admin.account.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenuDatarule<M extends BaseSysMenuDatarule<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return get("menu_id");
	}

	public M setFieldName(String fieldName) {
		set("field_name", fieldName);
		return (M)this;
	}

	public String getFieldName() {
		return get("field_name");
	}

	public M setSymbol(String symbol) {
		set("symbol", symbol);
		return (M)this;
	}

	public String getSymbol() {
		return get("symbol");
	}

	public M setValue(String value) {
		set("value", value);
		return (M)this;
	}

	public String getValue() {
		return get("value");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
